# Generated by Django 4.0.5 on 2022-10-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_room_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='helper_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='userdata',
            new_name='your_name',
        ),
    ]
